Makefile: Explicitly link against rt
The POSIX timer stuff requires linking against rt. Under RHEL 5, this
gets done indirectly. However due to a change in ld DSO linking around
the release of Fedora 13, when compiling receiptomatic under Fedora 14
you get the following errors:

.../www/receiptomatic-www.c:1981: undefined reference to 'timer_create'
.../www/receiptomatic-www.c:1988: undefined reference to 'timer_settime'

Specifying -lrt to gcc resolves this issue.

See https://fedoraproject.org/wiki/UnderstandingDSOLinkChange for
background.

Signed-off-by: Andrew Clayton <andrew@opentechlabs.co.uk>